// data.jsx — image-only gallery, auto-generated from assets/{fb,soc,gym}.
const PHOTOS = [
  { id:"f0", src:"assets/fb/DSC02301.jpg", cat:"Football" },
  { id:"f1", src:"assets/fb/DSC02361.jpg", cat:"Football" },
  { id:"f2", src:"assets/fb/DSC02445.jpg", cat:"Football" },
  { id:"f3", src:"assets/fb/DSC02589.jpg", cat:"Football" },
  { id:"f4", src:"assets/fb/DSC02906.jpg", cat:"Football" },
  { id:"f5", src:"assets/fb/DSC02912.jpg", cat:"Football" },
  { id:"f6", src:"assets/fb/DSC07730.jpg", cat:"Football" },
  { id:"f7", src:"assets/fb/DSC07795.jpg", cat:"Football" },
  { id:"f8", src:"assets/fb/DSC07811.jpg", cat:"Football" },
  { id:"f9", src:"assets/fb/DSC07840.jpg", cat:"Football" },
  { id:"f10", src:"assets/fb/DSC07872.jpg", cat:"Football" },
  { id:"f11", src:"assets/fb/DSC07952.jpg", cat:"Football" },
  { id:"f12", src:"assets/fb/DSC07995.jpg", cat:"Football" },
  { id:"f13", src:"assets/fb/DSC08064.jpg", cat:"Football" },
  { id:"f14", src:"assets/fb/DSC08074.jpg", cat:"Football" },
  { id:"f15", src:"assets/fb/DSC08091.jpg", cat:"Football" },
  { id:"f16", src:"assets/fb/DSC08108.jpg", cat:"Football" },
  { id:"f17", src:"assets/fb/DSC08124.jpg", cat:"Football" },
  { id:"f18", src:"assets/fb/DSC08148.jpg", cat:"Football" },
  { id:"f19", src:"assets/fb/DSC08176.jpg", cat:"Football" },
  { id:"f20", src:"assets/fb/DSC08196.jpg", cat:"Football" },
  { id:"f21", src:"assets/fb/DSC08200.jpg", cat:"Football" },
  { id:"f22", src:"assets/fb/DSC08246.jpg", cat:"Football" },
  { id:"f23", src:"assets/fb/DSC08270.jpg", cat:"Football" },
  { id:"f24", src:"assets/fb/DSC08383.jpg", cat:"Football" },
  { id:"f25", src:"assets/fb/DSC08395.jpg", cat:"Football" },
  { id:"f26", src:"assets/fb/DSC08708.jpg", cat:"Football" },
  { id:"f27", src:"assets/fb/DSC08755.jpg", cat:"Football" },
  { id:"f28", src:"assets/fb/DSC08871.jpg", cat:"Football" },
  { id:"s0", src:"assets/soc/DSC00007.jpg", cat:"Soccer" },
  { id:"s1", src:"assets/soc/DSC00027.jpg", cat:"Soccer" },
  { id:"s2", src:"assets/soc/DSC00064.jpg", cat:"Soccer" },
  { id:"s3", src:"assets/soc/DSC00083.jpg", cat:"Soccer" },
  { id:"s4", src:"assets/soc/DSC00092.jpg", cat:"Soccer" },
  { id:"s5", src:"assets/soc/DSC00115.jpg", cat:"Soccer" },
  { id:"s6", src:"assets/soc/DSC00129.jpg", cat:"Soccer" },
  { id:"s7", src:"assets/soc/DSC00177.jpg", cat:"Soccer" },
  { id:"s8", src:"assets/soc/DSC00219.jpg", cat:"Soccer" },
  { id:"s9", src:"assets/soc/DSC00237.jpg", cat:"Soccer" },
  { id:"s10", src:"assets/soc/DSC00248.jpg", cat:"Soccer" },
  { id:"s11", src:"assets/soc/DSC00276.jpg", cat:"Soccer" },
  { id:"s12", src:"assets/soc/DSC00295.jpg", cat:"Soccer" },
  { id:"s13", src:"assets/soc/DSC00311.jpg", cat:"Soccer" },
  { id:"s14", src:"assets/soc/DSC00332.jpg", cat:"Soccer" },
  { id:"s15", src:"assets/soc/DSC00351.jpg", cat:"Soccer" },
  { id:"s16", src:"assets/soc/DSC00369.jpg", cat:"Soccer" },
  { id:"s17", src:"assets/soc/DSC00378.jpg", cat:"Soccer" },
  { id:"s18", src:"assets/soc/DSC00386.jpg", cat:"Soccer" },
  { id:"s19", src:"assets/soc/DSC00428.jpg", cat:"Soccer" },
  { id:"s20", src:"assets/soc/DSC00433.jpg", cat:"Soccer" },
  { id:"s21", src:"assets/soc/DSC00472.jpg", cat:"Soccer" },
  { id:"s22", src:"assets/soc/DSC00480.jpg", cat:"Soccer" },
  { id:"s23", src:"assets/soc/DSC00522.jpg", cat:"Soccer" },
  { id:"s24", src:"assets/soc/DSC00539.jpg", cat:"Soccer" },
  { id:"s25", src:"assets/soc/DSC00551.jpg", cat:"Soccer" },
  { id:"s26", src:"assets/soc/DSC00596.jpg", cat:"Soccer" },
  { id:"s27", src:"assets/soc/DSC00660.jpg", cat:"Soccer" },
  { id:"s28", src:"assets/soc/DSC00663.jpg", cat:"Soccer" },
  { id:"s29", src:"assets/soc/DSC00688.jpg", cat:"Soccer" },
  { id:"s30", src:"assets/soc/DSC00703.jpg", cat:"Soccer" },
  { id:"s31", src:"assets/soc/DSC00709.jpg", cat:"Soccer" },
  { id:"s32", src:"assets/soc/DSC00720.jpg", cat:"Soccer" },
  { id:"s33", src:"assets/soc/DSC00732.jpg", cat:"Soccer" },
  { id:"s34", src:"assets/soc/DSC00744.jpg", cat:"Soccer" },
  { id:"s35", src:"assets/soc/DSC00756.jpg", cat:"Soccer" },
  { id:"s36", src:"assets/soc/DSC00816.jpg", cat:"Soccer" },
  { id:"s37", src:"assets/soc/DSC00826.jpg", cat:"Soccer" },
  { id:"s38", src:"assets/soc/DSC00862.jpg", cat:"Soccer" },
  { id:"s39", src:"assets/soc/DSC03055.jpg", cat:"Soccer" },
  { id:"s40", src:"assets/soc/DSC03386.jpg", cat:"Soccer" },
  { id:"s41", src:"assets/soc/DSC03481.jpg", cat:"Soccer" },
  { id:"s42", src:"assets/soc/DSC03489.jpg", cat:"Soccer" },
  { id:"s43", src:"assets/soc/DSC03537.jpg", cat:"Soccer" },
  { id:"s44", src:"assets/soc/DSC03742.jpg", cat:"Soccer" },
  { id:"s45", src:"assets/soc/DSC03808.jpg", cat:"Soccer" },
  { id:"s46", src:"assets/soc/DSC03840.jpg", cat:"Soccer" },
  { id:"s47", src:"assets/soc/DSC03870.jpg", cat:"Soccer" },
  { id:"s48", src:"assets/soc/DSC03886.jpg", cat:"Soccer" },
  { id:"s49", src:"assets/soc/DSC04071-2.jpg", cat:"Soccer" },
  { id:"s50", src:"assets/soc/DSC04071.jpg", cat:"Soccer" },
  { id:"s51", src:"assets/soc/DSC04081.jpg", cat:"Soccer" },
  { id:"s52", src:"assets/soc/DSC04221.jpg", cat:"Soccer" },
  { id:"s53", src:"assets/soc/DSC04354.jpg", cat:"Soccer" },
  { id:"s54", src:"assets/soc/DSC04546.jpg", cat:"Soccer" },
  { id:"s55", src:"assets/soc/DSC04704.jpg", cat:"Soccer" },
  { id:"s56", src:"assets/soc/DSC04860.jpg", cat:"Soccer" },
  { id:"s57", src:"assets/soc/DSC04984.jpg", cat:"Soccer" },
  { id:"s58", src:"assets/soc/DSC04986.jpg", cat:"Soccer" },
  { id:"s59", src:"assets/soc/DSC05316.jpg", cat:"Soccer" },
  { id:"s60", src:"assets/soc/DSC05429.jpg", cat:"Soccer" },
  { id:"s61", src:"assets/soc/DSC05531.jpg", cat:"Soccer" },
  { id:"s62", src:"assets/soc/DSC05600.jpg", cat:"Soccer" },
  { id:"s63", src:"assets/soc/DSC05721.jpg", cat:"Soccer" },
  { id:"s64", src:"assets/soc/DSC09024.jpg", cat:"Soccer" },
  { id:"s65", src:"assets/soc/DSC09028.jpg", cat:"Soccer" },
  { id:"s66", src:"assets/soc/DSC09192.jpg", cat:"Soccer" },
  { id:"s67", src:"assets/soc/DSC09298.jpg", cat:"Soccer" },
  { id:"s68", src:"assets/soc/DSC09304.jpg", cat:"Soccer" },
  { id:"s69", src:"assets/soc/DSC09332.jpg", cat:"Soccer" },
  { id:"s70", src:"assets/soc/DSC09428.jpg", cat:"Soccer" },
  { id:"s71", src:"assets/soc/DSC09443.jpg", cat:"Soccer" },
  { id:"s72", src:"assets/soc/DSC09489.jpg", cat:"Soccer" },
  { id:"s73", src:"assets/soc/DSC09504.jpg", cat:"Soccer" },
  { id:"s74", src:"assets/soc/DSC09505-2.jpg", cat:"Soccer" },
  { id:"s75", src:"assets/soc/DSC09505.jpg", cat:"Soccer" },
  { id:"s76", src:"assets/soc/DSC09532.jpg", cat:"Soccer" },
  { id:"s77", src:"assets/soc/DSC09575.jpg", cat:"Soccer" },
  { id:"s78", src:"assets/soc/DSC09585.jpg", cat:"Soccer" },
  { id:"s79", src:"assets/soc/DSC09589.jpg", cat:"Soccer" },
  { id:"s80", src:"assets/soc/DSC09593.jpg", cat:"Soccer" },
  { id:"s81", src:"assets/soc/DSC09743.jpg", cat:"Soccer" },
  { id:"s82", src:"assets/soc/DSC09812.jpg", cat:"Soccer" },
  { id:"s83", src:"assets/soc/DSC09932.jpg", cat:"Soccer" },
  { id:"s84", src:"assets/soc/DSC09973.jpg", cat:"Soccer" },
  { id:"g0", src:"assets/gym/DSC00601.jpg", cat:"Gymnastics" },
  { id:"g1", src:"assets/gym/DSC00812.jpg", cat:"Gymnastics" },
  { id:"g2", src:"assets/gym/DSC00865.jpg", cat:"Gymnastics" },
  { id:"g3", src:"assets/gym/DSC01888.jpg", cat:"Gymnastics" },
];

const CATS = [
  { id:"all", label:"All" },
  { id:"Football", label:"Football" },
  { id:"Soccer", label:"Soccer" },
  { id:"Gymnastics", label:"Gymnastics" },
];

const SERVICES = [
  { id:"match", icon:"Zap", name:"Game Day", price:"from $450",
    blurb:"One game, shot end to end \u2014 the kickoff, the grit, the bench erupting.",
    points:["Up to 3 hours on the sideline","60+ edited hi-res frames","48-hour gallery delivery","Full social crops"] },
  { id:"team", icon:"Camera", name:"Team & Portrait", price:"from $800", featured:true,
    blurb:"Squad portraits and individual hero shots that look like the back page.",
    points:["Studio or on-location","Full roster + coaching staff","Individual + team compositions","Print & licensing rights"] },
  { id:"season", icon:"Trophy", name:"Season Coverage", price:"let's talk",
    blurb:"I follow the whole campaign \u2014 every game, every meet, the whole arc.",
    points:["Priority booking, all events","Cumulative season archive","Highlight reel stills","Dedicated team portal"] },
];

const STATS = [
  { num:"10", suffix:"", label:"Seasons on the sideline" },
  { num:"180", suffix:"+", label:"Athletes & teams shot" },
  { num:"48", suffix:"hr", label:"Gallery turnaround" },
];

const MARQUEE = ["Football","Soccer","Gymnastics","Friday Nights","Team Portraits","Game Day","Season Archives","Senior Night"];

window.JPDATA = { PHOTOS, CATS, SERVICES, STATS, MARQUEE };
